import type { BugReport } from "@/lib/schemas";

export function reportToMarkdown(report: BugReport): string {
  const steps = report.stepsToReproduce.map((step, i) => `${i + 1}. ${step}`).join("\n");
  const env = report.environment;

  return `# ${report.title}

## Summary
${report.summary}

## Steps to Reproduce
${steps}

## Expected Behaviour
${report.expectedBehaviour}

## Actual Behaviour
${report.actualBehaviour}

## Environment
- **Browser:** ${env.browser}
- **OS:** ${env.os}
- **Device:** ${env.device}
- **App version:** ${env.appVersion}

## Severity
${report.severity} — ${report.explanations.severity}

## Priority
${report.priority} — ${report.explanations.priority}
${
  report.additionalNotes
    ? `\n## Additional Notes\n${report.additionalNotes}\n`
    : ""
}
---
*Confidence: ${report.confidence}% · Bug Quality Score: ${report.qualityScore}/100*
*Generated by BugPilot*
`;
}

/** Shape mirrors a typical Jira issue payload — not a real Jira API call, just the familiar structure. */
export function reportToJiraJson(report: BugReport) {
  const priorityNumber = Number(report.priority.replace("P", ""));

  return {
    fields: {
      project: { key: "PROJ" },
      issuetype: { name: "Bug" },
      summary: report.title,
      description: [
        report.summary,
        "",
        "Steps to Reproduce:",
        ...report.stepsToReproduce.map((s, i) => `${i + 1}. ${s}`),
        "",
        `Expected: ${report.expectedBehaviour}`,
        `Actual: ${report.actualBehaviour}`,
      ].join("\n"),
      priority: { name: `P${priorityNumber}` },
      labels: [report.severity.toLowerCase(), "bugpilot"],
      customfield_environment: {
        browser: report.environment.browser,
        os: report.environment.os,
        device: report.environment.device,
        appVersion: report.environment.appVersion,
      },
      customfield_severity: report.severity,
      customfield_confidence: report.confidence,
      customfield_bug_quality_score: report.qualityScore,
      customfield_additional_notes: report.additionalNotes || undefined,
    },
    meta: {
      generatedBy: "BugPilot",
      explanations: report.explanations,
    },
  };
}
